In [3]:
import numpy as np
print(np.__version__)

a = np.array([20,220,20])
a

1.25.1


array([ 20, 220,  20])

In [7]:
dir(a)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__class_getitem__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__dlpack__',
 '__dlpack_device__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__o

In [14]:
# creating a two-dimensional array
# Shape
b = np.array([[1,2,3],[3,4,4]])
b.shape

(2, 3)

In [15]:
b[1,2]

4

In [19]:
# creating an array of shape(2,3,4)
c = np.array([[[1,2,3,3],[4,3,5,6],[1,3,3,6]],[[7,87,3,9],[7,87,3,9],[3,456,56,56]]])
c.ndim

3

In [21]:
c[1,2,1]

456

In [22]:
c[1,2,2] = 565

In [23]:
c


array([[[  1,   2,   3,   3],
        [  4,   3,   5,   6],
        [  1,   3,   3,   6]],

       [[  7,  87,   3,   9],
        [  7,  87,   3,   9],
        [  3, 456, 565,  56]]])

In [24]:
np.array([0,4,3], dtype=complex)

array([0.+0.j, 4.+0.j, 3.+0.j])

In [26]:
arr = np.array([1,2,3,4], ndmin=5)
arr
arr.ndim

5

In [28]:
print(arr)

[[[[[1 2 3 4]]]]]


In [54]:
np.empty((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [30]:
x = np.zeros((4,3,2))
x

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [31]:
a

array([ 20, 220,  20])

In [32]:
k =np.ones_like(arr)

array([[[[[1, 1, 1, 1]]]]])

In [33]:
arr

array([[[[[1, 2, 3, 4]]]]])

In [39]:
np.zeros_like(x, dtype=float)

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [40]:
x.dtype

dtype('float64')

In [41]:
x

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [42]:
y = x.astype(int)

In [43]:
y

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0]]])

In [44]:
np.arange(1.5,6,0.5)

array([1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5])

In [45]:
np.linspace?


In [47]:
print(x.base)

None


In [50]:
np.linspace(1,5,10).reshape(2,5)

array([[1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778],
       [3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ]])

In [51]:
np.linspace(1,5,10,retstep=True)

(array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
        3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ]),
 0.4444444444444444)

In [52]:
np.linspace(1,5,10,retstep=False)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [53]:
np.linspace(1,5,10,retstep=True)

(array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
        3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ]),
 0.4444444444444444)

In [62]:
np.linspace(1,5,10,endpoint=True)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [63]:
arr = np.array([1,2,2,3,2,4,55])
arr

array([ 1,  2,  2,  3,  2,  4, 55])

In [65]:
arr1 =  np.array_split(arr,3)
arr1

[array([1, 2, 2]), array([3, 2]), array([ 4, 55])]

In [66]:
search = np.where(arr == 2)

In [67]:
search

(array([1, 2, 4], dtype=int64),)

In [70]:
#Initializing an array from a Function

def f(i,j):
    return 2*i*j

np.fromfunction(f,(4,3))

array([[ 0.,  0.,  0.],
       [ 0.,  2.,  4.],
       [ 0.,  4.,  8.],
       [ 0.,  6., 12.]])

In [71]:
np.fromfunction(lambda i,j: 2*i*j,(4,3))

array([[ 0.,  0.,  0.],
       [ 0.,  2.,  4.],
       [ 0.,  4.,  8.],
       [ 0.,  6., 12.]])

In [73]:
N, n = 20, 5
def f(i):
    return (i%n == 1)*1

comb =  np.fromfunction(f,(N,), dtype=int)
comb

array([0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0])

In [74]:
# a.shape will give the introspection of ndarray
b = np.array([[1,2,3],[3,4,4]])
b.shape #depth,lenght,width

(2, 3)

In [75]:
b.ndim


2

In [78]:
b.size
b.dtype
b.data


In [81]:
x = np.linspace(1,5,5)
x

array([1., 2., 3., 4., 5.])

In [82]:
x = np.linspace(1,5,5)
x**3

array([  1.,   8.,  27.,  64., 125.])

In [83]:
x-1

array([0., 1., 2., 3., 4.])

In [84]:
np.sqrt(x-1)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ])

In [92]:
y = np.exp(-np.linspace(0,2,5))
y
# np.sin(x-y)

array([1.        , 0.60653066, 0.36787944, 0.22313016, 0.13533528])

In [95]:
#matrix multiplication in numpy

a = np.array(((1,3),(2,1)))
b = a
a*b #element wise multiplication

array([[1, 9],
       [4, 1]])

In [96]:
b = a.T
b

array([[1, 2],
       [3, 1]])

In [97]:
np.matmul(a,b)

array([[10,  5],
       [ 5,  5]])

In [98]:
a.dot(b)

array([[10,  5],
       [ 5,  5]])

In [99]:
np.dot(a,b)

array([[10,  5],
       [ 5,  5]])

In [112]:
#Comparision and logic opera

a = np.array([[1,2,30],[2,3,400]])
a>100

array([[False, False, False],
       [False, False,  True]])

In [115]:
(a<10) | (a>100)

array([[ True,  True, False],
       [ True,  True,  True]])

In [128]:
# Creating an N*N ,magic square. N must be odd

N = 5
msquare = np.zeros((N,N),dtype = int)

n = 1
i,j = 0, N//2

while n <= N**2:
    msquare[i,j] = n
    n += 1
    newi, newj = (i-1)%N, (j+1)%N
    if msquare[newi, newj]:
        i += 1
    else:
        i,j = newi, newj
msquare

array([[17, 24,  1,  8, 15],
       [23,  5,  7, 14, 16],
       [ 4,  6, 13, 20, 22],
       [10, 12, 19, 21,  3],
       [11, 18, 25,  2,  9]])

In [133]:
a = np.array([[1,2,30],[2,3,400]])  
b = a.flatten()
b


array([  1,   2,  30,   2,   3, 400])

In [135]:
a = np.linspace(1,8,8)
a

array([1., 2., 3., 4., 5., 6., 7., 8.])

In [136]:
a.resize(2,2,2)
a

array([[[1., 2.],
        [3., 4.]],

       [[5., 6.],
        [7., 8.]]])

In [137]:
b = a.reshape(4,2)

In [138]:
b

array([[1., 2.],
       [3., 4.],
       [5., 6.],
       [7., 8.]])

In [7]:
a = np.linspace(1,16,16)
a = a.reshape(2,2,4)
a

array([[[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.]],

       [[ 9., 10., 11., 12.],
        [13., 14., 15., 16.]]])

In [11]:
a = np.array([[2,2],[3,3]])
a.transpose()

array([[2, 3],
       [2, 3]])

In [12]:
a.T

array([[2, 3],
       [2, 3]])

In [18]:
# np.vstack - nstack arrays vertically
# np.hstack - nstack arrays horizontally
# np.dstack - stack arrays depthwise

a = np.array([0,0,0,0])
b = np.array([1,1,1,1])
c = np.array([2,2,2,2])
d = np.vstack((a,b,c))
d

array([[0, 0, 0, 0],
       [1, 1, 1, 1],
       [2, 2, 2, 2]])

In [19]:
a = np.array([0,0,0,0])
b = np.array([1,1,1,1])
c = np.array([2,2,2,2])
d = np.hstack((a,b,c))
d

array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2])

In [20]:
a = np.array([0,0,0,0])
b = np.array([1,1,1,1])
c = np.array([2,2,2,2])
d = np.dstack((a,b,c))
d

array([[[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]]])

In [22]:
a = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [23]:
a[3,2]

12

In [24]:
a[:0]

array([], shape=(0, 3), dtype=int32)

In [25]:
a[:,1] #to get the second column

array([ 2,  5,  8, 11])

In [26]:
a[:,1] = 0 # setting every element in second column to 0

In [27]:
a

array([[ 1,  0,  3],
       [ 4,  0,  6],
       [ 7,  0,  9],
       [10,  0, 12]])

In [28]:
a = np.linspace(1,10,10)
a

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [30]:
ia = [1,4,5]
a[ia]

array([2., 5., 6.])

In [31]:
#adding a new axis

a = np.linspace(1,4,4).reshape(2,2)
a

array([[1., 2.],
       [3., 4.]])

In [33]:
b = a[::, np.newaxis]
b

array([[[1., 2.]],

       [[3., 4.]]])

In [34]:
a = np.array([[1,2,30],[2,3,400]])  
a

array([[  1,   2,  30],
       [  2,   3, 400]])

In [35]:
a.flatten()[4]

3

In [38]:
print(np.argmin(a))
print(np.argmax(a)) #argmin,argmax will give index


0
5


In [39]:
a.max()

400

In [41]:
a.max(axis=1) #max in row

array([ 30, 400])

In [42]:
a.max(axis=0) #max in col

array([  2,   3, 400])

In [43]:
a = np.array([0,7,7,7])
b = np.array([1,1,6,1])

np.fmax(a,b)

array([1, 7, 7, 7])

In [45]:
a = np.array([[0,0.6,1.2],[1.3,23.3,2.0]])
a


array([[ 0. ,  0.6,  1.2],
       [ 1.3, 23.3,  2. ]])

In [52]:
np.percentile(a,5) 

0.15

In [53]:
# np.mean - calculates the arithmatic mean along a specific axis
# np.average - calculates the weighted average
# np.median - calculates the median
# np.std - calculates standard deviation
# np.var - calculates the variance
# np.cov - calculates the covariance matrix
# np.corrcoef - calculates the correlation matrix

x = np.array([1,4,6,34])
np.mean(x)

11.25

In [54]:
np.median(x)

5.0

In [56]:
np.average(x, weights=[0.3,0,1,0])

4.846153846153846

In [57]:
np.std(x)

13.254716141811564

In [58]:
np.cov(x)

array(234.25)

In [70]:
#Special Distribution

# np.random = generate random numbers from any of several distributions
# .random_sample = create an array og given shape of R.V from uniform distributions[0,1)
# np.random.randint = take upon three arguments and return integer: low,high,size
# np.random.normal = select a random a samples from the normal distribution having mean - loc and standard deviation = scale, which default to 0 and 1 

In [62]:
np.random.seed(3)
np.random.randint(1,10,10)

array([9, 4, 9, 9, 1, 6, 4, 6, 8, 7])

In [63]:
np.random.randint(1,10,5)

array([1, 5, 8, 9, 2])

In [66]:
np.random.random_sample((2,3))

array([[0.35390507, 0.49263593, 0.91330145],
       [0.76582638, 0.97364827, 0.40236064]])

In [68]:
np.random.normal(x)

array([ 1.5024211 ,  2.40620519,  6.61335757, 35.58514359])

In [69]:
np.random.gamma?